spring:
  application:
    name:springboot-test
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "222222"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update